### ISSUE TITLE
Provide swagger.json with application

### ISSUE THREAD

**Issue by pjebs** [arsmn/fiber-swagger#1]
```go
	var (
		port = envInt("PORT", 4321)
		host = envString("HOST", fmt.Sprintf("http://localhost:%d", port))
	)

	app := fiber.New()
	docs.SwaggerInfo.Host = host
	app.Use("/docs", swagger.New(swagger.Config{ // custom
		URL:         host + "/swagger.json",
		DeepLinking: true,
	}))
	setUpRoutes(app)
```

**Comment by pjebs** [comment]
![image](https://user-images.githubusercontent.com/5377970/81889036-f6452f00-95e5-11ea-82d9-fb5643149f6f.png)

When I look at the generated `docs.go` file, I can see the swagger file inside as a text string.
Why does it seem I need to provide the `swagger.json` file with my application?

**Comment by arsmn** [comment]
You also should add prefix to your custom url.
```
       app.Use("/docs", swagger.New(swagger.Config{ // custom
		URL:         host + "/docs/swagger.json",
		DeepLinking: true,
	}))
```

**Comment by pjebs** [comment]
Do I still need to provide the swagger json file alongside the app for it to work?

**Comment by pjebs** [comment]
@arsmn It didn't work:


![image](https://user-images.githubusercontent.com/5377970/82113960-1d922c80-979d-11ea-8c64-659e139883c1.png)

![image](https://user-images.githubusercontent.com/5377970/82113965-2682fe00-979d-11ea-8cc2-03ea7cf63720.png)

**Comment by arsmn** [comment]
Yes when you set a custom url, your app should serve that.
See this link for serving static files
https://docs.gofiber.io/application#static
Or this one for serving embedded files
https://github.com/gofiber/embed

**Comment by pjebs** [comment]
When I comment out the URL and it uses the default, my app doesn't serve the swagger file still.
Does it use the swagger template string in docs.go in that case?

**Comment by pjebs** [comment]
Figured it out: Your pkg adds a route to `/docs/docs.json` which returns the template string inside `docs.go`.
