### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alhamsya** [arsmn/fiber-swagger#19]
![image](https://user-images.githubusercontent.com/56905970/159150407-e4ed42b9-f503-4057-a1a0-7d4866224e32.png)
![image](https://user-images.githubusercontent.com/56905970/159150411-cd2fd8d4-c9c3-4d29-a267-57c35a440831.png)
![image](https://user-images.githubusercontent.com/56905970/159150414-93a1f7a3-56cb-410e-96ff-37f424fbeec4.png)

**Comment by arsmn** [comment]
@alhamsya 
Do you have this issue with new version?
