### ISSUE TITLE
Cannot make Swagger route use the correct doc.json

### ISSUE THREAD

**Issue by felixveysseyre** [arsmn/fiber-swagger#3]
Hi !

I am trying to use your extension in order set-up correctly a _swagger_ endpoint.

I am very new to Go so it's kind of difficult to debug what's happening as I would like. Feel free to give me any advice.

I have carefully followed the instructions provided in your README file and was not able to get the swagger interface to display my project schema. It keeps displaying the default schema instead.

What I did :
- Installed `swag`
- Ran `swag init` to initialize the `./doc` directory with `docs.go`, `swagger.json`, `swagger.yaml`
- Added imports to my `main.go` file
- Added declarative comments to my `main.go` file
- Added the default handler to my `main.go` file
- Ran `swag init` to update the `./doc` directory files

`main.go`:
```go
package main

import (
	"fmt"
	swagger "github.com/arsmn/fiber-swagger"
	_ "github.com/arsmn/fiber-swagger/example/docs"
	"github.com/gofiber/fiber"
	configuration "gitlab.com/xxx/api-media-manager/pkg"
	"gitlab.com/xxx/api-media-manager/pkg/handlers"
)

// @title Media Manager API
// @version 1.0
// @description Media Manager service
func main() {
	/* Get configuration */

	mediaManagerConfiguration := configuration.New()

	/* Set-up server */

	server := fiber.New()

	server.Use("/swagger", swagger.Handler)

	server.Get("/*", handlers.ReadImage)

	/* Run server */

	address := fmt.Sprintf("%s:%d", mediaManagerConfiguration.Host, mediaManagerConfiguration.Port)

	server.Listen(address)
}
```

Taking a look at `./doc` directory files, they are up to date and contain the information defined in my `main.go` file.

Thanks for your help !

**Comment by felixveysseyre** [comment]
Finally found the answer to my question.

 I needed to import the correct docs directory:

```go
import (
    _ "gitlab.com/xxx/api-media-manager/docs"
)
```

Instead of:

```go
import (
    _ "github.com/arsmn/fiber-swagger/example/docs"
)
```

**Comment by rchgonzaga** [comment]
It was not clear for me either, thanks for sharing this Felix.

**Comment by cjtim** [comment]
i was getting `not yet registered swag` when fetching `doc.json`

after include 
```golang
import (
    _ "github.com/your_repo/docs"
)
```
problem solved
Thank you
