### ISSUE TITLE
JWT Authorization Annotations

### ISSUE THREAD

**Issue by sebastianbuechler** [arsmn/fiber-swagger#5]
Which annotations do we need to use for JWT Authorization?

It seems that Swagger is implementing this via bearerAuth: https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by raymayemir** [comment]
Hi @sebastianbuechler ! I use it like this `// @Param Authorization header string true "Bearer"`

**Comment by sebastianbuechler** [comment]
Hi @raymayemir, thanks for your reply.

This can work for endpoints, but how can we integrate the authorization in the main declaration? For example instead of this:
```
// @securitydefinitions.oauth2.implicit OAuth2Implicit
// @authorizationurl https://example.com/oauth/authorize
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information
```

**Comment by raymayemir** [comment]
@sebastianbuechler if you look at the [list](https://swaggo.github.io/swaggo.io/declarative_comments_format/general_api_info.html#security) this option is not available yet. You can try using a different generator :) I am also interested in this possibility

**Comment by arsmn** [comment]
Thank you @raymayemir

**Comment by sebastianbuechler** [comment]
@arsmn Why do you consider this closed? The issue remains.

**Comment by arsmn** [comment]
@sebastianbuechler I think it's better to open an issue for [swaggo](https://github.com/swaggo/swag) to support that option you want

**Comment by sebastianbuechler** [comment]
@arsmn The respecting PR are already filed in swaggo and go-openapi: https://github.com/go-openapi/spec/pull/122 and https://github.com/swaggo/swag/pull/805
However, the projects seem to have quite some PRs open for a long time, so I don't know how fast the can be merged into the projects.
