### ISSUE TITLE
The case of first letter of field names is not respect the JSON serialize rule

### ISSUE THREAD

**Issue by weaming** [arsmn/fiber-swagger#8]
```
type Type struct {
    FirstName string
}
```
will be in JSON format:
```
{ "FirstName": "xxx"}
```
but the docs render it as
```
{ "firstName": "xxx"}
```

**Comment by arsmn** [comment]
It seems default case style used in [swag](https://github.com/swaggo/swag) is camelCase
However you can set json tag explicitly:
```
type Type struct {
    FirstName string `json:"FirstName"`
}
```

**Comment by weaming** [comment]
Then `swag` should respect the default style of JSON serialization in Go, I think.

**Comment by arsmn** [comment]
There is also a property strategy option
https://github.com/swaggo/swag#swag-cli

**Comment by weaming** [comment]
Thanks!
